jobs:
  include:
    - stage: "All"
      name: "Docker Tests"
      dist: trusty
      services:
        - docker
      install: docker pull holochain/holochain-cmd:develop
      script:
        - . docker/run-ci
    - name: "windows build"
      os: windows
      language: rust
      rust: nightly-2018-10-12-x86_64-pc-windows-msvc
      script:
      - rustup target add wasm32-unknown-unknown --toolchain nightly-2018-10-12-x86_64-pc-windows-msvc
      - cargo build --verbose --all
      - cargo test --verbose --all