services:
  - docker

dist: trusty

jobs:
  include:
    - stage: "All"
      name: "Tests"
      install: docker pull holochain/holochain-cmd:holoconsole-to-hcshell
      script:
        - . docker/run-ci