#!/bin/bash
#rustup toolchain install nightly-x86_64-unknown-linux-gnu
#rustup toolchain install nightly-2018-07-17-x86_64-unknown-linux-gnu
#cargo +nightly-2018-07-17-x86_64-unknown-linux-gnu install fmt
#rustup default nightly

cd /holochain/holochain-cmd
git reset --hard
git pull
git submodule init
git submodule update
cargo update

cd /holochain/holosqape
git reset --hard
git pull
git submodule init
git submodule update

echo "COMPILING HOLOCHAIN RUST"
cd /holochain/holosqape/holochain-rust
cargo update
cargo +$TOOLS_NIGHTLY build --release

echo "COMPILING HOLOSQAPE BINDINGS"
cd /holochain/holosqape/bindings
make clean
qmake CONFIG+=release
make

echo "COMPILING hcshell"
cd /holochain/holosqape/hcshell
make clean
qmake CONFIG+=release
make
