#!/bin/bash
#rustup toolchain install nightly-x86_64-unknown-linux-gnu
#rustup toolchain install nightly-2018-07-17-x86_64-unknown-linux-gnu
#cargo +nightly-2018-07-17-x86_64-unknown-linux-gnu install fmt
#rustup default nightly

cd /holochain/holosqape
git pull
git submodule init
git submodule update

echo "COMPILING HOLORUST"
cd /holochain/holosqape/holochain-rust
cargo update
cargo +$TOOLS_NIGHTLY build --release


echo "COMPILING HOLOSQAPE BINDINGS"
cd /holochain/holosqape/bindings
qmake
make

echo "COMPILING HOLOCONSOLE"
cd /holochain/holosqape/holoconsole
qmake CONFIG+=release
make
